// Copyright (c) 2024-2026 Bios Tlt. Licensed under Apache License 2.0.
//

package com.wps4pin.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme — green-tinted to match original Swift pastel green
val md_theme_light_primary = Color(0xFF1B6B3A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA4F5B8)
val md_theme_light_onPrimaryContainer = Color(0xFF00210E)
val md_theme_light_secondary = Color(0xFF4F6352)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E8D1)
val md_theme_light_onSecondaryContainer = Color(0xFF0D1F12)
val md_theme_light_tertiary = Color(0xFF3A6470)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBDE9F8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFC0F0C6)
val md_theme_light_onBackground = Color(0xFF00210E)
val md_theme_light_surface = Color(0xFFC0F0C6)
val md_theme_light_onSurface = Color(0xFF00210E)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_outlineVariant = Color(0xFFC1C9BF)

// Dark scheme
val md_theme_dark_primary = Color(0xFF88D89E)
val md_theme_dark_onPrimary = Color(0xFF00391C)
val md_theme_dark_primaryContainer = Color(0xFF00522C)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F5B8)
val md_theme_dark_secondary = Color(0xFFB5CCB6)
val md_theme_dark_onSecondary = Color(0xFF213527)
val md_theme_dark_secondaryContainer = Color(0xFF384B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E8D1)
val md_theme_dark_tertiary = Color(0xFFA2CDDB)
val md_theme_dark_onTertiary = Color(0xFF023640)
val md_theme_dark_tertiaryContainer = Color(0xFF214C58)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDE9F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00210E)
val md_theme_dark_onBackground = Color(0xFFC0F0C6)
val md_theme_dark_surface = Color(0xFF00210E)
val md_theme_dark_onSurface = Color(0xFFC0F0C6)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BF)
val md_theme_dark_outline = Color(0xFF8B938A)
val md_theme_dark_outlineVariant = Color(0xFF414942)
